import type { EndpointSpec } from './parametrosGobernanzaTypes';
import { TENANT_SUPERADMIN_INSERT_ENDPOINTS } from './tenantSuperAdminInsertEndpoints';

export const ENDPOINTS: EndpointSpec[] = [
  { id: 'tenant-listar-libres', section: 'tenant', actor: 'ambos', method: 'GET', path: '/api/config/global/creacion/usu/tenant/libres', title: 'Listar tenantSuperAdmin visibles', description: 'Solo registros tenantSuperAdmin (sin tenantGlobal). Alcance según JWT.', fields: [] },
  {
    id: 'tenant-listar-libres-superadmin',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'GET',
    path: '/api/config/global/creacion/usu/tenant/libres',
    title: 'Listar tenantSuperAdmin (rama JWT)',
    description: 'tenantSuperAdmin visibles para tu sesión (jerarquía DIOS / SA). No incluye tenantGlobal.',
    fields: [],
  },
  {
    id: 'tenant-listar-libres-tenantglobal',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'GET',
    path: '/api/config/global/creacion/usu/tenant/libres',
    title: 'Listar tenantGlobal',
    description: 'Misma API: lista tenantSuperAdmin alcanzables desde el tenantGlobal del JWT.',
    fields: [],
  },
  {
    id: 'tenant-crear-global-usuario',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/global/creacion/usu/tenant/global',
    title: 'Crear tenant global desde tenantGlobal',
    description:
      'Flujo puro tenantGlobal sobre su propia rama descendente. NVL de generación se resuelve en servidor desde tu tenant (generacionGlobalNvlRolesConfig).',
    fields: [
      { name: 'coporativo', label: 'Corporativo (empresa)', type: 'id' },
      { name: 'tenantGlobalRef', label: 'Tenant global ref', type: 'id' },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id', required: true },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id', required: true },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id', required: true },
    ],
  },
  {
    id: 'tenant-crear-global-admin',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'POST',
    path: '/api/config/global/creacion/superAdmin/tenant/global',
    title: 'Crear tenant Administrador del sistema',
    description:
      'Contrato exclusivo con tenantSuperAdmin (JWT): sin rol tenantGlobal en este flujo. El servidor valida alcance de tu rama SA y corporativo frente a tenantjerarquiacounters cuando aplica.',
    fields: [
      { name: 'nvlGeneracionTenant', label: 'Nivel generacion tenant', type: 'id', required: true },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id', required: true },
      { name: 'coporativo', label: 'Corporativo (empresa)', type: 'id' },
      { name: 'tenantGlobalRef', label: 'Tenant global ref', type: 'id' },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id', required: true },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id', required: true },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id', required: true },
    ],
  },
  ...TENANT_SUPERADMIN_INSERT_ENDPOINTS,
  {
    id: 'tenant-actualizar-global',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'PUT',
    path: '/api/config/global/actualizar/tenant/global/:id',
    title: 'Actualizar tenant global',
    description: 'Actualiza tenant global por id.',
    fields: [
      { name: 'id', label: 'ID tenant global', type: 'id', required: true, pathParam: true },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id' },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id' },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id' },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id' },
    ],
  },
  {
    id: 'tenant-desactivar-global',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/global/desactivar/tenant/global/:id',
    title: 'Desactivar tenant global',
    description: 'Desactiva tenant global sin eliminar.',
    fields: [{ name: 'id', label: 'ID tenant global', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'tenant-eliminar-global',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/global/eliminar/tenant/global/:id',
    title: 'Eliminar tenant global',
    description: 'Elimina tenant global de forma definitiva.',
    fields: [{ name: 'id', label: 'ID tenant global', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'tenant-crear-global-reglas',
    section: 'reglas',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/tenant/tipo/crear/globales/reglas/jerarquia/roles',
    title: 'Crear reglas globales',
    description: 'Formulario principal para crear reglas de jerarquia.',
    primary: true,
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id', required: true },
      { name: 'contextoDefi', label: 'Contexto', type: 'context', required: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos', required: true },
      {
        name: 'politicasRuntimeIds',
        label: 'Políticas runtime (BYPASS / ALLOW / DENY)',
        type: 'politicasRuntime',
        required: false,
      },
    ],
  },
  { id: 'tenant-listar-reglas', section: 'reglas', actor: 'ambos', method: 'GET', path: '/api/config/tenant/listar/reglas', title: 'Listar reglas tenant', description: 'Consulta de reglas creadas.', fields: [] },
  {
    id: 'tenant-actualizar-global-reglas',
    section: 'reglas',
    actor: 'ambos',
    method: 'PUT',
    path: '/api/config/tenant/tipo/actualizar/globales/reglas/jerarquia',
    title: 'Actualizar reglas globales',
    description: 'Actualiza regla global usando header x-regla-id.',
    fields: [
      { name: 'x-regla-id', label: 'x-regla-id', type: 'id', required: true, header: true },
      { name: 'contextoDefi', label: 'Contexto', type: 'context', required: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos', required: true },
      {
        name: 'politicasRuntimeIds',
        label: 'Políticas runtime (BYPASS / ALLOW / DENY)',
        type: 'politicasRuntime',
        required: false,
      },
    ],
  },
  {
    id: 'tenant-desactivar-global-reglas',
    section: 'reglas',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/tenant/tipo/desactivar/globales/reglas/jerarquia',
    title: 'Desactivar regla global',
    description: 'Desactiva una regla global usando header x-regla-id.',
    fields: [
      { name: 'x-regla-id', label: 'x-regla-id', type: 'id', required: true, header: true },
    ],
  },
  {
    id: 'tenant-eliminar-global-reglas',
    section: 'reglas',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/tenant/tipo/eliminar/globales/reglas/jerarquia',
    title: 'Eliminar regla global',
    description: 'Elimina una regla global usando header x-regla-id.',
    fields: [
      { name: 'x-regla-id', label: 'x-regla-id', type: 'id', required: true, header: true },
    ],
  },
  {
    id: 'tenant-crear-dios-reglas',
    section: 'reglas',
    actor: 'tenantSuperAdmin',
    method: 'POST',
    path: '/api/config/tenant/tipo/crear/dios/reglas/jerarquia/roles',
    title: 'Crear regla DIOS',
    description:
      'Crea la regla de plataforma para el rol DIOS. Multi-tenant, usuarios por rama, recursos, acciones y políticas runtime vinculadas por id.',
    fields: [
      { name: 'tenantSuperAdmin', label: 'Tenant SuperAdmin', type: 'id', required: false },
      { name: 'dominioTenatGlobales', label: 'Dominio', type: 'dominioDinamico', required: false },
      { name: 'securityPlatform', label: 'Security platform', type: 'text', required: false },
      { name: 'contexto', label: 'Contexto', type: 'text', required: false },
      {
        name: 'politicasRuntimeIds',
        label: 'Políticas runtime (BYPASS / ALLOW / DENY)',
        type: 'politicasRuntime',
        required: false,
      },
    ],
  },
  {
    id: 'tenant-actualizar-dios-reglas',
    section: 'reglas',
    actor: 'tenantSuperAdmin',
    method: 'PUT',
    path: '/api/config/tenant/tipo/actualizar/dios/reglas/jerarquia/roles',
    title: 'Actualizar regla DIOS',
    description:
      'Sincroniza regla plataforma por alcance (tenant SA + usuarios opcionales) y actualiza políticas runtime vinculadas.',
    fields: [
      { name: 'tenantSuperAdmin', label: 'Tenant SuperAdmin', type: 'id', required: false },
      { name: 'dominioTenatGlobales', label: 'Dominio', type: 'dominioDinamico', required: false },
      { name: 'securityPlatform', label: 'Security platform', type: 'text', required: false },
      { name: 'contexto', label: 'Contexto', type: 'text', required: false },
      {
        name: 'politicasRuntimeIds',
        label: 'Políticas runtime (BYPASS / ALLOW / DENY)',
        type: 'politicasRuntime',
        required: false,
      },
    ],
  },
  {
    id: 'tenant-listar-dios-reglas',
    section: 'reglas',
    actor: 'tenantSuperAdmin',
    method: 'GET',
    path: '/api/config/tenant/tipo/listar/dios/reglas/jerarquia/roles/:tenantSuperAdmin',
    title: 'Listar reglas DIOS',
    description:
      'Lista las reglas DIOS activas del Tenant SuperAdmin seleccionado. El backend valida el rol DIOS y el alcance del JWT.',
    fields: [
      { name: 'tenantSuperAdmin', label: 'Tenant SuperAdmin', type: 'id', required: true, pathParam: true },
    ],
  },
  {
    id: 'tenant-eliminar-dios-reglas',
    section: 'reglas',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/tenant/tipo/eliminar/dios/reglas/jerarquia/roles/:tenantSuperAdmin/:id',
    title: 'Eliminar regla DIOS',
    description:
      'Elimina una regla DIOS por id, limitada al Tenant SuperAdmin seleccionado y al dominio del sistema.',
    fields: [
      { name: 'tenantSuperAdmin', label: 'Tenant SuperAdmin', type: 'id', required: true, pathParam: true },
      { name: 'id', label: 'ID regla DIOS', type: 'id', required: true, pathParam: true },
    ],
  },
  { id: 'perm-listar-herencias', section: 'permisos', actor: 'ambos', method: 'GET', path: '/api/config/permisos/listar/usu/tenant/libres', title: 'Listar herencias', description: 'Lista permisos heredados del usuario autenticado.', fields: [] },
  {
    id: 'perm-usuario-tenant-global',
    section: 'permisos',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/usu/tenant/global',
    title: 'Asignar parametrizacion global',
    description: 'Asigna parametrizacion al usuario autenticado con seleccion de vistas y acciones.',
    fields: [],
  },
  {
    id: 'perm-admin-tenant-global',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'POST',
    path: '/api/config/permisos/creacion/admin/superadmin/global',
    title: 'Permisos heredados (solo tenantSuperAdmin)',
    description:
      'Solo sesión SuperAdmin (DIOS). El desplegable de alcance respeta tenantJerarquiaCounter: sin corporativo ves todos los TG; con corporativo asociado, solo la rama de tu SA.',
    fields: [
      { name: 'tenantGlobal', label: 'tenantSuperAdmin', type: 'id', required: true },
      { name: 'tenantCorporativo', label: 'Tenant corporativo', type: 'id' },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos', required: true },
    ],
  },
  {
    id: 'perm-admin-tenant-global-listar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'GET',
    path: '/api/config/permisos/creacion/admin/tenant/global?incluirSuperAdmin=false',
    title: 'Listar herencias admin/global',
    description: 'Lista registros creados en flujo admin/tenant/global.',
    fields: [],
  },
  {
    id: 'perm-admin-tenant-global-actualizar-sa',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'PUT',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id',
    title: 'Actualizar herencia admin/global (SuperAdmin)',
    description:
      'Actualiza una herencia por id. Sesión tenantSuperAdmin (DIOS): alcance y selects alineados con «Permisos heredados» (POST).',
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id' },
      { name: 'herenciaAsociada', label: 'Herencia asociada', type: 'id', required: true, pathParam: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos' },
    ],
  },
  {
    id: 'perm-admin-tenant-global-actualizar-tg',
    section: 'permisos',
    actor: 'tenantGlobal',
    method: 'PUT',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id',
    title: 'Actualizar herencia admin/global (Tenant global)',
    description:
      'Actualiza una herencia por id. Sesión tenantGlobal (ADMIN): solo herencias de tu TG.',
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id' },
      { name: 'herenciaAsociada', label: 'Herencia asociada', type: 'id', required: true, pathParam: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos' },
    ],
  },
  {
    id: 'perm-admin-tenant-global-desactivar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id',
    title: 'Desactivar herencia admin/global',
    description: 'Desactiva registro sin eliminar fÃ­sicamente.',
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id' },
      { name: 'herenciaAsociada', label: 'Herencia asociada', type: 'id', required: true, pathParam: true },
      { name: 'id', label: 'ID herencia', type: 'id', required: true, pathParam: true },
    ],
  },
  {
    id: 'perm-admin-tenant-global-eliminar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id/force',
    title: 'Eliminar herencia admin/global',
    description: 'EliminaciÃ³n definitiva (requiere estar desactivada).',
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id' },
      { name: 'herenciaAsociada', label: 'Herencia asociada', type: 'id', required: true, pathParam: true },
      { name: 'id', label: 'ID herencia', type: 'id', required: true, pathParam: true },
    ],
  },
  // â”€â”€ CORPORATIVO â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'corp-listar-tenant', section: 'corporativo', actor: 'ambos', method: 'GET', path: '/api/config/permisos/corporativo/listar/tenant', title: 'Listar tenant corporativos', description: 'Lista los tenantCorporativos visibles para el usuario autenticado.', fields: [] },
  {
    id: 'corp-crear-tenant',
    section: 'corporativo',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/corporativo/crear/tenant',
    title: 'Crear tenant corporativo',
    description: 'Crea un nuevo tenantCorporativo asociado al tenantGlobal del JWT.',
    fields: [
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel corporativo (nvlGeneracionCoporativoTenant)', type: 'id', required: true },
    ],
  },
  {
    id: 'corp-actualizar-tenant',
    section: 'corporativo',
    actor: 'ambos',
    method: 'PUT',
    path: '/api/config/permisos/corporativo/actualizar/tenant/:id',
    title: 'Actualizar tenant corporativo',
    description: 'Actualiza coporativo y/o nvlGeneracionCoporativoTenant de un tenantCorporativo.',
    fields: [
      { name: 'id', label: 'ID tenant corporativo', type: 'id', required: true, pathParam: true },
      { name: 'coporativo', label: 'Corporativo (id perfilCorporativo)', type: 'id' },
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel corporativo', type: 'id' },
    ],
  },
  {
    id: 'corp-desactivar-tenant',
    section: 'corporativo',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/desactivar/tenant/:id',
    title: 'Desactivar tenant corporativo',
    description: 'Soft-delete: marca el tenantCorporativo como inactivo.',
    fields: [{ name: 'id', label: 'ID tenant corporativo', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'corp-eliminar-tenant',
    section: 'corporativo',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/eliminar/tenant/:id',
    title: 'Eliminar tenant corporativo',
    description: 'EliminaciÃ³n fÃ­sica definitiva de un tenantCorporativo.',
    fields: [{ name: 'id', label: 'ID tenant corporativo', type: 'id', required: true, pathParam: true }],
  },
  // CatÃ¡logo (tipo comprador)
  { id: 'corp-listar-catalogo', section: 'corporativo', actor: 'ambos', method: 'GET', path: '/api/config/permisos/corporativo/listar/catalogo', title: 'Listar catÃ¡logo tipos comprador', description: 'Lista los tipos de comprador corporativo activos.', fields: [] },
  {
    id: 'corp-crear-catalogo',
    section: 'corporativo',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/corporativo/guardar/catologo/tenant/corporativo',
    title: 'Crear tipo comprador corporativo',
    description: 'Crea un nuevo tipo de comprador (categoria de rol) corporativo.',
    fields: [
      { name: 'tipo_comprador', label: 'Tipo comprador', type: 'text', required: true },
      { name: 'sigla', label: 'Sigla', type: 'text', required: true },
    ],
  },
  {
    id: 'corp-modificar-catalogo',
    section: 'corporativo',
    actor: 'ambos',
    method: 'PUT',
    path: '/api/config/permisos/corporativo/modificar/catalogo/:id',
    title: 'Modificar tipo comprador',
    description: 'Actualiza tipo_comprador y/o sigla de una categorÃ­a de comprador.',
    fields: [
      { name: 'id', label: 'ID tipo comprador', type: 'id', required: true, pathParam: true },
      { name: 'tipo_comprador', label: 'Tipo comprador', type: 'text' },
      { name: 'sigla', label: 'Sigla', type: 'text' },
    ],
  },
  {
    id: 'corp-desactivar-catalogo',
    section: 'corporativo',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/desactivar/catalogo/:id',
    title: 'Desactivar tipo comprador',
    description: 'Soft-delete del tipo de comprador corporativo.',
    fields: [{ name: 'id', label: 'ID tipo comprador', type: 'id', required: true, pathParam: true }],
  },
  // Roles corporativos
  {
    id: 'corp-crear-rol',
    section: 'corporativo',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/corporativo/guardar/roles/tenant/corporativo',
    title: 'Crear rol base corporativo',
    description: 'Crea un rol base para el contexto corporativo.',
    fields: [
      { name: 'rol', label: 'Nombre del rol', type: 'text', required: true },
    ],
  },
  // Niveles globales
  { id: 'corp-listar-nvl-global', section: 'corporativo', actor: 'ambos', method: 'GET', path: '/api/config/permisos/corporativo/listar/nvl/global', title: 'Listar niveles scope global', description: 'Lista los nvlPermisosCor de scope global (sin tenantCorporativo asignado).', fields: [] },
  {
    id: 'corp-crear-nvl-global',
    section: 'corporativo',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/corporativo/crear/tenant/nvl/corporativo',
    title: 'Crear nivel scope global',
    description: 'Crea un nivel jerÃ¡rquico corporativo de scope global.',
    fields: [
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'accionesPermitidas', label: 'Acciones permitidas (IDs, JSON array)', type: 'json', required: true },
      { name: 'heredarPermisos', label: 'Heredar permisos (true/false)', type: 'text' },
    ],
  },
  {
    id: 'corp-modificar-nvl-global',
    section: 'corporativo',
    actor: 'ambos',
    method: 'PUT',
    path: '/api/config/permisos/corporativo/modificar/nvl/global/:id',
    title: 'Modificar nivel scope global',
    description: 'Actualiza nombre, heredarPermisos, accionesPermitidas de un nivel global.',
    fields: [
      { name: 'id', label: 'ID nivel', type: 'id', required: true, pathParam: true },
      { name: 'nombre', label: 'Nombre', type: 'text' },
      { name: 'heredarPermisos', label: 'Heredar permisos (true/false)', type: 'text' },
      { name: 'accionesPermitidas', label: 'Acciones permitidas (IDs, JSON array)', type: 'json' },
    ],
  },
  {
    id: 'corp-desactivar-nvl-global',
    section: 'corporativo',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/desactivar/nvl/global/:id',
    title: 'Desactivar nivel scope global',
    description: 'Soft-delete del nivel corporativo global.',
    fields: [{ name: 'id', label: 'ID nivel', type: 'id', required: true, pathParam: true }],
  },
  // Niveles scope corporativo
  { id: 'corp-listar-nvl-corp', section: 'corporativo', actor: 'ambos', method: 'GET', path: '/api/config/permisos/corporativo/listar/nvl/corporativo', title: 'Listar niveles scope corporativo', description: 'Lista los nvlPermisosCor con tenantCorporativo asignado.', fields: [] },
  {
    id: 'corp-crear-nvl-corp',
    section: 'corporativo',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/corporativo/guardar/nvl/corporativo',
    title: 'Crear nivel scope corporativo',
    description: 'Crea un nivel jerÃ¡rquico vinculado a un tenantCorporativo especÃ­fico.',
    fields: [
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'tenantGlobalId', label: 'Tenant global (si ejecutor es DIOS)', type: 'id' },
    ],
  },
  {
    id: 'corp-modificar-nvl-corp',
    section: 'corporativo',
    actor: 'ambos',
    method: 'PUT',
    path: '/api/config/permisos/corporativo/modificar/nvl/corp/:id',
    title: 'Modificar nivel scope corporativo',
    description: 'Actualiza campos de un nvlPermisosCor de scope corporativo.',
    fields: [
      { name: 'id', label: 'ID nivel', type: 'id', required: true, pathParam: true },
      { name: 'nombre', label: 'Nombre', type: 'text' },
      { name: 'heredarPermisos', label: 'Heredar permisos (true/false)', type: 'text' },
    ],
  },
  {
    id: 'corp-desactivar-nvl-corp',
    section: 'corporativo',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/desactivar/nvl/corp/:id',
    title: 'Desactivar nivel scope corporativo',
    description: 'Soft-delete del nivel corporativo especÃ­fico.',
    fields: [{ name: 'id', label: 'ID nivel', type: 'id', required: true, pathParam: true }],
  },
  // Parametrizacion SA â†’ TG
  { id: 'corp-listar-parametrizacion', section: 'corporativo', actor: 'ambos', method: 'GET', path: '/api/config/permisos/corporativo/listar/parametrizacion', title: 'Listar parametrizacion SAâ†’TG', description: 'Lista las parametrizaciones que controlan cuÃ¡ntos corporativos puede crear cada tenantGlobal.', fields: [] },
  {
    id: 'corp-guardar-parametrizacion',
    section: 'corporativo',
    actor: 'tenantSuperAdmin',
    method: 'POST',
    path: '/api/config/permisos/corporativo/guardar/parametrizacion',
    title: 'Crear parametrizacion SAâ†’TG',
    description: 'Solo SUPER_ADMIN. Define si el tenantGlobal puede crear corporativos y cuÃ¡ntos.',
    fields: [
      { name: 'tenantGlobalId', label: 'Tenant global ID', type: 'id', required: true },
      { name: 'canCreateCorporativos', label: 'Puede crear corporativos (true/false)', type: 'text', required: true },
      { name: 'maxCorporativos', label: 'Max corporativos (nÃºmero, opcional)', type: 'text' },
    ],
  },
  {
    id: 'corp-modificar-parametrizacion',
    section: 'corporativo',
    actor: 'tenantSuperAdmin',
    method: 'PUT',
    path: '/api/config/permisos/corporativo/modificar/parametrizacion/:id',
    title: 'Modificar parametrizacion SAâ†’TG',
    description: 'Actualiza canCreateCorporativos y/o maxCorporativos de una parametrizaciÃ³n.',
    fields: [
      { name: 'id', label: 'ID parametrizacion', type: 'id', required: true, pathParam: true },
      { name: 'canCreateCorporativos', label: 'Puede crear corporativos (true/false)', type: 'text' },
      { name: 'maxCorporativos', label: 'Max corporativos', type: 'text' },
    ],
  },
  {
    id: 'corp-desactivar-parametrizacion',
    section: 'corporativo',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/desactivar/parametrizacion/:id',
    title: 'Desactivar parametrizacion SAâ†’TG',
    description: 'Marca la parametrizaciÃ³n como inactiva (el TG pierde permiso de crear corporativos).',
    fields: [{ name: 'id', label: 'ID parametrizacion', type: 'id', required: true, pathParam: true }],
  },
  // Herencia de permisos corporativos
  {
    id: 'corp-crear-herencia',
    section: 'corporativo',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/permisos/corporativo/crear/herencia/permisos/tenant',
    title: 'Crear herencia permisos corporativo',
    description: 'Asigna acciones y vistas a un usuario dentro de un tenantCorporativo.',
    fields: [
      { name: 'usuarioId', label: 'Usuario ID', type: 'id', required: true },
      { name: 'rolId', label: 'Rol corporativo ID', type: 'id', required: true },
      { name: 'tenantCorporativoId', label: 'Tenant corporativo ID', type: 'id', required: true },
      { name: 'acciones', label: 'Acciones (IDs, JSON array)', type: 'json', required: true },
      { name: 'vistas', label: 'Vistas (IDs, JSON array)', type: 'json' },
      { name: 'tenantGlobal', label: 'Tenant global (si ejecutor es DIOS)', type: 'id' },
    ],
  },
];
