import { EndpointSpec, HttpMethod } from './types';

export const METHOD_STYLE: Record<HttpMethod, string> = {
  GET: 'bg-blue-100 text-blue-700 border-blue-200',
  POST: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  PUT: 'bg-amber-100 text-amber-700 border-amber-200',
  DELETE: 'bg-red-100 text-red-700 border-red-200',
};

export const ENDPOINTS: EndpointSpec[] = [
  { id: 'tenant-listar-libres', section: 'tenant', actor: 'ambos', method: 'GET', path: '/api/config/global/creacion/usu/tenant/libres', title: 'Listar tenants visibles', description: 'Listado de tenants visibles para el usuario autenticado.', fields: [] },
  {
    id: 'tenant-crear-corporativo-global',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/global/creacion/usu/tenant/corporativo',
    title: 'Crear tenant corporativo (global)',
    description: 'Crea tenant corporativo desde flujo de tenant global.',
    fields: [
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel generacion corporativo', type: 'id', required: true },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id', required: true },
      { name: 'ownerType', label: 'Owner type', type: 'id', required: true },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id', required: true },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id', required: true },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id', required: true },
    ],
  },
  {
    id: 'tenant-actualizar-global',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'PUT',
    path: '/api/config/global/actualizar/tenant/global/:id',
    title: 'Actualizar tenant global',
    description: 'Actualiza tenant global por id.',
    fields: [
      { name: 'id', label: 'ID tenant global', type: 'id', required: true, pathParam: true },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id' },
      { name: 'ownerType', label: 'Owner type', type: 'id' },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id' },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id' },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id' },
    ],
  },
  {
    id: 'tenant-desactivar-global',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/global/desactivar/tenant/global/:id',
    title: 'Desactivar tenant global',
    description: 'Desactiva tenant global sin eliminar.',
    fields: [{ name: 'id', label: 'ID tenant global', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'tenant-eliminar-global',
    section: 'tenant',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/global/eliminar/tenant/global/:id',
    title: 'Eliminar tenant global',
    description: 'Elimina tenant global de forma definitiva.',
    fields: [{ name: 'id', label: 'ID tenant global', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'tenant-crear-global-reglas',
    section: 'tenant',
    actor: 'ambos',
    method: 'POST',
    path: '/api/config/tenant/tipo/crear/globales/reglas/jerarquia/roles',
    title: 'Crear reglas globales',
    description: 'Formulario principal para crear reglas de jerarquia.',
    primary: true,
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id', required: true },
      { name: 'contextoDefi', label: 'Contexto', type: 'context', required: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos', required: true },
    ],
  },
  { id: 'tenant-listar-reglas', section: 'tenant', actor: 'ambos', method: 'GET', path: '/api/config/tenant/listar/reglas', title: 'Listar reglas tenant', description: 'Consulta de reglas creadas.', fields: [] },
  {
    id: 'tenant-actualizar-global-reglas',
    section: 'tenant',
    actor: 'ambos',
    method: 'PUT',
    path: '/api/config/tenant/tipo/actualizar/globales/reglas/jerarquia',
    title: 'Actualizar reglas globales',
    description: 'Actualiza regla global usando header x-regla-id.',
    fields: [
      { name: 'x-regla-id', label: 'x-regla-id', type: 'id', required: true, header: true },
      { name: 'contextoDefi', label: 'Contexto', type: 'context', required: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos', required: true },
    ],
  },
  {
    id: 'tenant-desactivar-global-reglas',
    section: 'tenant',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/tenant/tipo/desactivar/globales/reglas/jerarquia',
    title: 'Desactivar regla global',
    description: 'Desactiva una regla global usando header x-regla-id.',
    fields: [{ name: 'x-regla-id', label: 'x-regla-id', type: 'id', required: true, header: true }],
  },
  {
    id: 'tenant-eliminar-global-reglas',
    section: 'tenant',
    actor: 'ambos',
    method: 'DELETE',
    path: '/api/config/tenant/tipo/eliminar/globales/reglas/jerarquia',
    title: 'Eliminar regla global',
    description: 'Elimina una regla global usando header x-regla-id.',
    fields: [{ name: 'x-regla-id', label: 'x-regla-id', type: 'id', required: true, header: true }],
  },
  { id: 'perm-listar-herencias', section: 'permisos', actor: 'ambos', method: 'GET', path: '/api/config/permisos/listar/usu/tenant/libres', title: 'Listar herencias', description: 'Lista permisos heredados del usuario autenticado.', fields: [] },
  {
    id: 'perm-usuario-tenant-global',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'POST',
    path: '/api/config/permisos/usu/tenant/global',
    title: 'Asignar parametrizacion global',
    description: 'Asigna parametrizacion al usuario autenticado con seleccion de vistas y acciones.',
    fields: [{ name: 'heredaGlobal', label: 'Herencia global', type: 'id', required: true }],
  },
  {
    id: 'perm-admin-tenant-global',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'POST',
    path: '/api/config/permisos/creacion/admin/tenant/global',
    title: 'Asignar permisos heredados',
    description: 'Flujo para tenantSuperAdmin (DIOS).',
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id', required: true },
      { name: 'tenantCorporativo', label: 'Tenant corporativo', type: 'id' },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos', required: true },
    ],
  },
  {
    id: 'perm-admin-tenant-global-listar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'GET',
    path: '/api/config/permisos/creacion/admin/tenant/global',
    title: 'Listar herencias admin/global',
    description: 'Lista registros creados en flujo admin/tenant/global.',
    fields: [],
  },
  {
    id: 'perm-admin-tenant-global-actualizar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'PUT',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id',
    title: 'Actualizar herencia admin/global',
    description: 'Actualiza una herencia por id.',
    fields: [
      { name: 'tenantGlobal', label: 'Tenant global', type: 'id' },
      { name: 'herenciaAsociada', label: 'Herencia asociada', type: 'id', required: true, pathParam: true },
      { name: 'permisos', label: 'Permisos por vista/accion', type: 'permisos' },
    ],
  },
  {
    id: 'perm-admin-tenant-global-desactivar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id',
    title: 'Desactivar herencia admin/global',
    description: 'Desactiva registro sin eliminar fisicamente.',
    fields: [{ name: 'id', label: 'ID herencia', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'perm-admin-tenant-global-eliminar',
    section: 'permisos',
    actor: 'tenantSuperAdmin',
    method: 'DELETE',
    path: '/api/config/permisos/creacion/admin/tenant/global/:id/force',
    title: 'Eliminar herencia admin/global',
    description: 'Eliminacion definitiva (requiere estar desactivada).',
    fields: [{ name: 'id', label: 'ID herencia', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'perm-crear-coporativo',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/creacion/usu/tenant/coporativo',
    title: 'Crear tenant corporativo',
    description: 'Flujo tenantGlobal (ADMIN).',
    fields: [
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel generacion corporativo', type: 'id', required: true },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id', required: true },
      { name: 'ownerType', label: 'Owner type', type: 'id', required: true },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id', required: true },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id', required: true },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id', required: true },
    ],
  },
  {
    id: 'perm-crear-corporativo-alias',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/creacion/usu/tenant/corporativo',
    title: 'Crear tenant corporativo (alias)',
    description: 'Alias canonico del endpoint corporativo.',
    fields: [
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel generacion corporativo', type: 'id', required: true },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id', required: true },
      { name: 'ownerType', label: 'Owner type', type: 'id', required: true },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id', required: true },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id', required: true },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id', required: true },
    ],
  },
  {
    id: 'perm-actualizar-corporativo',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'PUT',
    path: '/api/config/permisos/corporativo/actualizar/tenant/:id',
    title: 'Actualizar herencia corporativa',
    description: 'Actualiza datos del tenant corporativo por id.',
    fields: [
      { name: 'id', label: 'ID registro', type: 'id', required: true, pathParam: true },
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel generacion corporativo', type: 'id' },
      { name: 'tipo_tenant', label: 'Tipo tenant', type: 'id' },
      { name: 'ownerType', label: 'Owner type', type: 'id' },
      { name: 'apisDominios', label: 'Apis dominios', type: 'id' },
      { name: 'accionesUsu', label: 'Accion usuario', type: 'id' },
      { name: 'rolesMabs', label: 'Rol mabs', type: 'id' },
    ],
  },
  {
    id: 'perm-desactivar-corporativo',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/desactivar/tenant/:id',
    title: 'Desactivar registro (opcional)',
    description: 'Desactiva herencia corporativa sin eliminar fisicamente.',
    fields: [{ name: 'id', label: 'ID registro', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'perm-eliminar-corporativo',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'DELETE',
    path: '/api/config/permisos/corporativo/eliminar/tenant/:id',
    title: 'Eliminar registro (opcional)',
    description: 'Elimina registro corporativo de forma definitiva.',
    fields: [{ name: 'id', label: 'ID registro', type: 'id', required: true, pathParam: true }],
  },
  {
    id: 'perm-corporativo-guardar-catalogo',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/corporativo/guardar/catologo/tenant/corporativo',
    title: 'Guardar catalogo corporativo',
    description: 'Crea catalogo de tipo comprador corporativo.',
    fields: [
      { name: 'tipo_comprador', label: 'Tipo comprador', type: 'text', required: true },
      { name: 'sigla', label: 'Sigla', type: 'text', required: true },
    ],
  },
  {
    id: 'perm-corporativo-guardar-rol',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/corporativo/guardar/roles/tenant/corporativo',
    title: 'Guardar rol corporativo',
    description: 'Crea rol corporativo para tenant.',
    fields: [{ name: 'rol', label: 'Rol', type: 'text', required: true }],
  },
  {
    id: 'perm-corporativo-crear-tenant',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/corporativo/crear/tenant',
    title: 'Crear tenant corporativo (modulo corporativo)',
    description: 'Crea tenant corporativo desde modulo corporativo.',
    fields: [
      { name: 'coporativo', label: 'Corporativo (ID o valor)', type: 'text' },
      { name: 'nvlGeneracionCoporativoTenant', label: 'Nivel generacion corporativo', type: 'id', required: true },
      { name: 'tenantGlobalId', label: 'Tenant global destino', type: 'id' },
    ],
  },
  {
    id: 'perm-corporativo-crear-herencia',
    section: 'permisos',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/corporativo/crear/herencia/permisos/tenant',
    title: 'Crear herencia permisos corporativos',
    description: 'Asigna herencia de vistas y acciones a tenant corporativo.',
    fields: [
      { name: 'usuarioId', label: 'Usuario destino', type: 'id' },
      { name: 'rolId', label: 'Rol ID', type: 'id', required: true },
      { name: 'tenantCorporativoId', label: 'Tenant corporativo ID', type: 'id', required: true },
      { name: 'tenantGlobal', label: 'Tenant global ID', type: 'id' },
      { name: 'acciones', label: 'Acciones (array JSON)', type: 'json', required: true, placeholder: '["id_accion_1","id_accion_2"]' },
      { name: 'vistas', label: 'Vistas (array JSON)', type: 'json', placeholder: '["id_vista_1","id_vista_2"]' },
    ],
  },
  {
    id: 'perm-corporativo-crear-nivel',
    section: 'tenant',
    actor: 'tenantGlobal',
    method: 'POST',
    path: '/api/config/permisos/corporativo/crear/tenant/nvl/corporativo',
    title: 'Crear nivel corporativo',
    description: 'Crea nivel corporativo con acciones permitidas.',
    fields: [
      { name: 'nombre', label: 'Nombre del nivel', type: 'text', required: true },
      { name: 'accionesPermitidas', label: 'Acciones permitidas (array JSON)', type: 'json', required: true, placeholder: '["crear","editar","ver"]' },
      { name: 'heredarPermisos', label: 'Heredar permisos (true/false)', type: 'json', placeholder: 'true' },
      { name: 'tenantGlobalId', label: 'Tenant global ID', type: 'id' },
    ],
  },
];
